name: RivalsPlugin
version: 0.2
author: Silveros
main: net.silveros.main.RivalsPlugin
api-version: 1.14

commands:
  kit:
    description: Gives the specified kit to the player/command executor.
    permission: rivals.kit
    usage: /kit <kit>

  kitp:
    description: Gives the specified kit to the specified player.
    permission: rivals.kit
    usage: /kit <player> <kit>

  rteam:
    description: Sets what Rivals team the specified player is on.
    permission: rivals.rteam
    usage: /rteam <player> <team>

  energy:
    description: Sets the specified player's energy count.
    permission: rivals.energy
    usage: /energy <player> <amount>

  score:
    description: Sets the specified team's Dominate score.
    permission: rivals.score
    usage: /score <team> <amount>

  setuppoints:
    description: Test command for setting up or resetting capture points.
    permission: rivals.setuppoints
    usage: /setuppoints <start/reset>

  start:
    description: Begins a new game.
    permission: rivals.start
    usage: /start <map (optional)>

permissions: {}