name: RivalsPlugin
version: 1.0
author: Silveros
main: net.silveros.main.RivalsPlugin
api-version: 1.14

commands:
  kit:
    description: Gives the specified kit to the player
    permission: rivals.kit
    usage: /kit <kit>

  rteam:
    description: Sets what Rivals team the specified player is on.
    permission: rivals.rteam
    usage: /rteam <team>

permissions: {}